apiVersion: keti.example.com/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: openmcp-deployment-example
  namespace: keti
spec:
  replicas: 6
  labels:
      app: nginx
  template:
    spec:
      template:
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "1Mi"
                cpu: "100m"
