apiVersion:  openmcp.k8s.io/v1alpha1
kind: OpenMCPIngress
metadata:
  name: openmcp-ingress-keti
  namespace: openmcp
spec:
  template:
    spec:
      rules:
        - host: openmcp.service.org
          http:
            paths:
              - backend:
                  serviceName: iot-gateway-svc
                  servicePort: 80
