apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPService
metadata:
  name: openmcp-service-example
  namespace: keti
spec:
  template:
    spec:
      type: LoadBalancer
      ports:
        - name: http
          port: 80
  labelselector:
    app: nginx
