apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: snapshots.openmcp.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: openmcp.k8s.io
  names:
    kind: Snapshot
    listKind: SnapshotList
    plural: snapshots
    singular: snapshot
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Created time stamp
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: '-'
      jsonPath: .status.Status
      name: IsSuccess
      type: boolean
    - description: '-'
      jsonPath: .spec.snapshotSources[*].resourceCluster
      name: Cluster
      type: string
    - description: '-'
      jsonPath: .spec.snapshotSources[*].resourceNamespace
      name: NameSpace
      type: string
    - description: '-'
      jsonPath: .spec.groupSnapshotKey
      name: GroupSnapshotKey
      type: string
    - description: '-'
      jsonPath: .status.isVolumeSnapshot
      name: IsVolumeSnapshot
      type: boolean
    - description: '-'
      jsonPath: .status.Reason
      name: REASON
      type: string
    - description: ElapsedTime
      jsonPath: .status.ElapsedTime
      name: ElapsedTime
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Snapshot is the Schema for the snapshots API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SnapshotSpec defines the desired state of Snapshot
            properties:
              groupSnapshotKey:
                type: string
              snapshotPolicy:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                properties:
                  maxSnapshots:
                    description: MaxSnapshots is to specify how many snapshots we
                      want to keep 0 is magic number to indicate un-limited snapshots
                    type: integer
                  snapshotIntervalInSecond:
                    description: SnapshotIntervalInSecond is to specify how often
                      operator take snapshot 0 is magic number to indicate one-shot
                      snapshot
                    format: int64
                    type: integer
                  timeoutInSecond:
                    description: TimeoutInSecond is the maximal allowed time in second
                      of the entire snapshot process.
                    format: int64
                    type: integer
                type: object
              snapshotSources:
                items:
                  description: SnapshotSource contains the supported snapshot sources.
                  properties:
                    resourceCluster:
                      type: string
                    resourceName:
                      type: string
                    resourceNamespace:
                      type: string
                    resourceSnapshotKey:
                      type: string
                    resourceType:
                      type: string
                    volumeDataSource:
                      description: VolumeDataSource contains the supported snapshot
                        sources.
                      properties:
                        volumeSnapshotClassName:
                          type: string
                        volumeSnapshotKey:
                          type: string
                        volumeSnapshotSourceKind:
                          type: string
                        volumeSnapshotSourceName:
                          type: string
                      required:
                      - volumeSnapshotKey
                      type: object
                  required:
                  - resourceCluster
                  - resourceName
                  - resourceNamespace
                  - resourceType
                  type: object
                type: array
            required:
            - snapshotSources
            type: object
          status:
            description: SnapshotStatus defines the observed state of Snapshot
            properties:
              ElapsedTime:
                description: LastSuccessDate indicate the time to get snapshot last
                  time LastSuccessDate metav1.Time `json:"lastSuccessDate,omitempty"`
                type: string
              Reason:
                description: Reason indicates the reason for any backup related failures.
                type: string
              ReasonDetail:
                type: string
              Status:
                description: Status indicates if the backup has Succeeded.
                type: boolean
              isVolumeSnapshot:
                description: isVolumeSnapshot
                type: boolean
              snapshotSource:
                items:
                  description: SnapshotSource contains the supported snapshot sources.
                  properties:
                    resourceCluster:
                      type: string
                    resourceName:
                      type: string
                    resourceNamespace:
                      type: string
                    resourceSnapshotKey:
                      type: string
                    resourceType:
                      type: string
                    volumeDataSource:
                      description: VolumeDataSource contains the supported snapshot
                        sources.
                      properties:
                        volumeSnapshotClassName:
                          type: string
                        volumeSnapshotKey:
                          type: string
                        volumeSnapshotSourceKind:
                          type: string
                        volumeSnapshotSourceName:
                          type: string
                      required:
                      - volumeSnapshotKey
                      type: object
                  required:
                  - resourceCluster
                  - resourceName
                  - resourceNamespace
                  - resourceType
                  type: object
                type: array
            required:
            - Reason
            - Status
            - snapshotSource
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
