apiVersion: keti.example.com/v1alpha1
kind: OpenMCPPolicyEngine
metadata:
  name: hpa-target-cluster
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPHybridAutoScaler
      policies:
        - type: Target
          value:
            - cluster1
            - cluster2
            - cluster3
  rangeOfApplication: All
  policyStatus: Enabled
