apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: analytic-metrics-weight
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPAnalyticEngine
      policies:
        - type: CPU
          value:
            - "0.2"
        - type: Memory
          value:
            - "0.2"
        - type: FS
          value:
            - "0.2"
        - type: NET
          value:
            - "0.8"
        - type: LATENCY
          value:
            - "0.5"
        - type: GeoRate
          value:
            - "0.8"
  policyStatus: Enabled
