apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: loadbalancing-controller-policy
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: OpenMCPLoadbalancingController
      policies:
        - type: GeoRate
          value:
            - "0.9"
        - type: Period
          value:
            - "5.0"
        - type: RegionZoneMatchedScore
          value:
            - "100"
        - type: OnlyRegionMatchedScore
          value:
            - "1"
        - type: NoRegionZoneMatchedScore
          value:
            - "1"
  policyStatus: Enabled
