apiVersion: v1
kind: Service
metadata:
  name: openmcp-analytic-engine
  namespace: openmcp
  annotations:
    metallb.universe.tf/allow-shared-ip: openmcp
  labels:
    name: openmcp-analytic-engine
  
spec:
  type: LoadBalancer
  ports:
  - port: 2050
    targetPort: 2050
    nodePort: 30001
    protocol: TCP
  selector:
    name: openmcp-analytic-engine
