apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-loadbalancing-controller2
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-loadbalancing-controller2
  template:
    metadata:
      labels:
        name: openmcp-loadbalancing-controller2
    spec:
      serviceAccountName: openmcp-loadbalancing-controller2
      imagePullSecrets:
        - name: regcred
      containers:
        - name: openmcp-loadbalancing-controller2
          # Replace this with the built image name
          image: ketidevit/openmcp-loadbalancing-controller2:v0.0.1
          command:
          - openmcp-loadbalancing-controller2
          imagePullPolicy: Always
          env:
            - name: GRPC_SERVER
              value: 10.0.3.20
            - name: GRPC_PORT
              value: "32050"
            - name: WATCH_NAMESPACE
              value: ""
              #valueFrom:
              #  fieldRef:
              #    fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "loadbalancing-controller2"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
