apiVersion: v1
kind: Service
metadata:
  name: openmcp-loadbalancing-controller2
  namespace: openmcp
spec:
  selector:
    name: openmcp-loadbalancing-controller2
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer