apiVersion: v1
kind: Service
metadata:
  name: openmcp-metric-collector
  namespace: openmcp
  labels:
    name: openmcp-metric-collector
spec:
  type: LoadBalancer
  ports:
  - port: 2051
    targetPort: 2051
    nodePort: 32051
    protocol: TCP
  selector:
    name: openmcp-metric-collector
