apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-configmap-controller
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-configmap-controller
  template:
    metadata:
      labels:
        name: openmcp-configmap-controller
    spec:
      serviceAccountName: openmcp-configmap-controller
      imagePullSecrets:
        - name: REPLACE_DOCKERSECRETNAME
      containers:
        - name: openmcp-configmap-controller
          # Replace this with the built image name
          image: REPLACE_DOCKERREGISTRYIP/openmcp/openmcp-configmap-controller:v0.0.1
          command:
          - openmcp-configmap-controller
          imagePullPolicy: REPLACE_DOCKERIMAGEPULLPOLICY
          env:
            - name: WATCH_NAMESPACE
              #value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openmcp-configmap-controller"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
