apiVersion:  keti.example.com/v1alpha1
kind: OpenMCPIngress
metadata:
  name: example-openmcpingress
  namespace: openmcp
spec:
  template:
    spec:
      rules:
      - host: loadbalancing.openmcp.org
        http:
          paths:
          - path: /validation
            backend:
              serviceName: iot-gateway-svc
              servicePort: 80


