apiVersion: keti.example.com/v1alpha1
kind: Sync
metadata:
  name: openmcp-deployment-sync-2
  namespace: openmcp
spec:
  clustername: cluster1
  command: update
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      namespace: openmcp
      annotations:
        multicluster.admiralty.io/controller-reference: '{"apiVersion":"keti.example.com/v1alpha1","kind":"OpenMCPDeployment","name":"openmcp-pod-test","uid":"740f7d83-0da2-432d-93bf-2cc620b5b56d","controller":true,"blockOwnerDeletion":true,"clusterName":"openmcp","namespace":"test"}'
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 3 # tells deployment to run 2 pods matching the template
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.7.9
              ports:
                - containerPort: 80
