apiVersion: keti.example.com/v1alpha1
kind: Sync
metadata:
  name: openmcp-service-sync-3
  namespace: openmcp
spec:
  clustername: cluster1
  command: delete
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-svc
      namespace: openmcp
