apiVersion: keti.example.com/v1alpha1
kind: Sync
metadata:
  name: openmcp-service-sync-2
  namespace: openmcp
spec:
  clustername: cluster1
  command: update
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-svc
      namespace: openmcp
      labels:
        app: nginx
      annotations:
        multicluster.admiralty.io/controller-reference: '{"apiVersion":"keti.example.com/v1alpha1","kind":"OpenMCPService","name":"example-openmcpservice","uid":"b22b7506-b969-4589-ab1f-63c166588583","controller":true,"blockOwnerDeletion":true,"clusterName":"openmcp","namespace":"openmcp"}'
    spec:
      type: LoadBalancer
      ports:
        - port: 81
          targetPort: 81
          protocol: TCP
      selector:
        app: nginx
