apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmcp-snapshot
  namespace: openmcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openmcp-snapshot
  template:
    metadata:
      labels:
        name: openmcp-snapshot
    spec:
      serviceAccountName: openmcp-snapshot-sa
      imagePullSecrets:
        - name: regcred
      containers:
        - name: openmcp-snapshot
          # Replace this with the built image name
          image: openmcp/openmcp-snapshot:v0.0.2
          command:
          - openmcp-snapshot
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "openmcp-snapshot"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
        
  
